on: push
  issues:
    types: [opened]
name: Create new tickets in Jira
jobs:
  build:
    runs-on: ubuntu-latest
    name: Create new tickets in Jira
    steps:
      - name: Login to Jira
        uses: acquia/gajira-login-2@server
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      - name: Create Jira ticket
        id: create
        uses: acquia/gajira-create@server
        with:
          project: DX
          issuetype: Task
          summary: ${{ github.events.issue.title }}
          description: ${{ github.events.issue.url }}
          fields: '{"components": [{"id": "20084"}]}'
      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
#      - name: Update Github issue with Jira ticket prefix
#        uses: actions-cool/issues-helper@v3
#        with:
#          actions: 'update-issue'
#          token: ${{ secrets.GITHUB_TOKEN }}
#          issue-number: ${{ github.event.issue.number }}
#          state: 'open'
#          title: "${{ steps.create.outputs.issue }}: ${{ github.event.issue.number }}"