on:
  release:
    types: [prereleased]

jobs:
  create-ticket:
    runs-on: ubuntu-latest
    name: Create a CCB ticket in Jira
    steps:
      - run: | 
          curl \
          -D- \
          -u $USER:PASSWORD \
          -X POST \
          --data "{ \
            \"fields\": { \
              \"project\": { \
                \"key\": \"${JIRA_PROJECT_ID}\", \
              }" \
              \"summary\": \"the summary\", \
              \"description\": \"the description\", \
              \"issuetype\": { \
                \"name\": \"task\", \
              }" \
            }" \
          -H "Content-Type: application/json" \
          $JIRA_BASE_API_URL/$JIRA_PROJECT_ID/issue/
        shell: bash
